# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-01 18:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charamount', models.FloatField(verbose_name='amount charged')),
                ('charstate', models.CharField(choices=[('successful', 'successful'), ('pending', 'pending'), ('failed', 'failed')], max_length=10, verbose_name='charge state')),
                ('chartime', models.DateTimeField(default=datetime.datetime.now, verbose_name='charge time')),
                ('creditnum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.CreditCard', verbose_name='creditcard number')),
                ('logname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="user's logname")),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.Project', verbose_name='project name')),
            ],
            options={
                'verbose_name': 'charge',
                'verbose_name_plural': 'charge',
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, verbose_name='comments')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('logname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="user's logname")),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.Project', verbose_name='project name')),
            ],
            options={
                'verbose_name': 'projectcomment',
                'verbose_name_plural': 'projectcomment',
            },
        ),
        migrations.CreateModel(
            name='ProjectRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratelevel', models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5, verbose_name='ratelevel')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('logname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="user's logname")),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.Project', verbose_name='project name')),
            ],
            options={
                'verbose_name': 'projectrate',
                'verbose_name_plural': 'projectrate',
            },
        ),
        migrations.CreateModel(
            name='UserFavourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.IntegerField(default=0, verbose_name='id')),
                ('fav_type', models.IntegerField(choices=[(1, 'user'), (2, 'project')], default=1, verbose_name='favourite type')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('logname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="user's logname")),
            ],
            options={
                'verbose_name': 'favourite',
                'verbose_name_plural': 'favourite',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='receive user')),
                ('message', models.CharField(max_length=500, verbose_name='message content')),
                ('has_read', models.BooleanField(default=False, verbose_name='if read')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
            ],
            options={
                'verbose_name': 'user message',
                'verbose_name_plural': 'user message',
            },
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('logname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="user's logname")),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.Project', verbose_name='project name')),
            ],
            options={
                'verbose_name': "user's project",
                'verbose_name_plural': "user's project",
            },
        ),
    ]
