# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-01 18:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50, verbose_name='project name')),
                ('pdescription', models.CharField(max_length=300, verbose_name='project description')),
                ('tag', models.CharField(max_length=20, verbose_name='project category description')),
                ('mingoal', models.FloatField(verbose_name='min funds needed')),
                ('maxgoal', models.FloatField(verbose_name='max funds needed')),
                ('actualamount', models.FloatField(verbose_name='actual funds collected')),
                ('posttime', models.DateTimeField(default=datetime.datetime.now, verbose_name='post date of request')),
                ('endtime', models.DateTimeField(verbose_name='end date of request')),
                ('completetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='complete time of request')),
                ('pstate', models.CharField(choices=[('live', 'live'), ('canceled', 'canceled'), ('suspend', 'suspend'), ('failed', 'failed'), ('successful', 'successful')], max_length=10, verbose_name='project state')),
                ('likesnum', models.IntegerField(default=0, verbose_name='likes number')),
                ('image', models.ImageField(upload_to='Project/%Y/%m', verbose_name='project image')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'project',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stitle', models.CharField(max_length=50, verbose_name='title of sample')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='add time')),
                ('download', models.FileField(upload_to='Project/resource/%Y/%m', verbose_name='sample file')),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.Project', verbose_name='project name')),
            ],
            options={
                'verbose_name': 'sample',
                'verbose_name_plural': 'sample',
            },
        ),
    ]
